version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: api-container
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_URI=${DB_URI}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - PORT=${PORT}
      - FRONTEND_URL=${FRONTEND_URL}
      - EMAIL_SENDER_USER=${EMAIL_SENDER_USER}
      - EMAIL_SENDER_PASSWORD=${EMAIL_SENDER_PASSWORD}
      - EMAIL_SENDER_HOST=${EMAIL_SENDER_HOST}
      - EMAIL_SENDER_PORT=${EMAIL_SENDER_PORT}
    env_file:
      - .env
    command: npm run start:dev
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mongo:5.0
    ports:  
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge